### ISSUE TITLE
About dimension of features and vad labels

### ISSUE THREAD

**Issue by SteveTanggithub** [bagustris/dimensional-ser#3]
plz use hst.npy for features and keep the dimension of features as (10039,*)and vad as (10039,3),you can cancel the code :vad= vad.reshape(-1,1)

**Comment by bagustris** [comment]
In this case (without normalization), the label of valence, arousal, and dominance is in original format, that is, from 1 to 5 scale. I normalized the labels into [-1, 1] for two purposes: (1) follow the previous research, and (2) obtain better (CCC) performance. Once,you are able to run the code you can experiment to normalize the labels, as well as the input features.

Features have dimension (10039, 1, 68) for LSTM input, and labels have (10039, 3) size.
