### ISSUE TITLE
Word embeddings

### ISSUE THREAD

**Issue by revelation12** [bagustris/dimensional-ser#7]
Great paper. Do you have code for word embeddings acquisition (i.e. that was used to generate x_train_text.npy and g_word_embedding_matrix.npy)? I'm also working with the IEMOCAP dataset and this would be very helpful. Thanks! @bagustris

**Comment by bagustris** [comment]
Hi there @revelation12 .

Have  a look in my another repository: https://github.com/bagustris/Apsipa2019_SpeechText
Particularly in text emotion recognition part > https://github.com/bagustris/Apsipa2019_SpeechText/blob/master/code/python_files/text_emo.ipynb

x_train_text.npy  is saved from the output of line 13 (Jupyter notebook line), 
while g_word_embedding_matrix is saved from the output of line 14. 
Please note that the line is not in order.
(And this is the reason I switch from Jupyter notebook to plain python files).
