### ISSUE TITLE
Request for SEWA Dataset

### ISSUE THREAD

**Issue by SteveTanggithub** [bagustris/dimensional-ser#8]
Could you plz provide the SEWA database? We saw your paper in 2020ICASSP used the dataset. We have sent the request to SEWA team, but didn't get reply. We only use it for academic research.

**Comment by bagustris** [comment]
Sorry I can't. My 2020 ICASSP paper used AVEC 2019 dataset, which is part of SEWA dataset. Please contact the organizer to obtain the dataset.
